# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4]
        laravel: ['6.*', '7.*', '8.*']

    name: 'PHP ${{ matrix.php }} / ${{ matrix.laravel }}'

    steps:
      - uses: actions/checkout@master

      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '${{ matrix.php }}'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: none

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer install

      # Install legacy factories for Laravel 8
      - name: Install legacy factories for Laravel
        if: ${{ matrix.laravel == '8.*' }}
        run: composer require laravel/legacy-factories

      # Display installed laravel version
      - name: Show laravel version
        run: composer show laravel/framework

      # Run phpunit tests
      - name: Run tests
        run: ./vendor/bin/phpunit
